=== Krycho/Qubic/qubic/resources/qcmapping.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://www.example.org/Qubic"
           xmlns:qc="http://www.example.org/Qubic">
	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
        <xs:element name="map" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="fromType" type="xs:string" use="required"/>
            <xs:attribute name="toType" type="xs:string" use="required"/>
          </xs:complexType>  
        </xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Krycho/Qubic/qubic/resources/qcmapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<qc:mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:qc="http://www.example.org/Qubic"
       xsi:schemaLocation="http://www.example.org/Qubic qcmapping.xsd">

	   <qc:map fromType="char" toType="QcStringField"/>
	   <qc:map fromType="varchar" toType="QcStringField"/>
	   <qc:map fromType="text" toType="QcStringField"/>
	   
	   <qc:map fromType="int" toType="QcIntegerField"/>
	   <qc:map fromType="smallint" toType="QcIntegerField"/>
	   <qc:map fromType="tinyint" toType="QcIntegerField"/>
	   <qc:map fromType="mediumint" toType="QcIntegerField"/>
	   <qc:map fromType="decimal" toType="QcIntegerField"/>
	   
	   <qc:map fromType="datetime" toType="QcDateField"/>
	   <qc:map fromType="year" toType="QcDateField"/>
	   
	   <qc:map fromType="timestamp" toType="QcTimestampField"/>
	   
	   	<qc:map fromType="enum" toType="QcEnumField"/>
		   
	   <qc:map fromType="float" toType="QcFloatField"/>
	   
	   <qc:map fromType="blob" toType="QcBlobField"/>

</qc:mapping>
